#!/bin/bash
./build
docker build -t gcr.io/hightowerlabs/konfd:0.0.1 .
gcloud docker -- push gcr.io/hightowerlabs/konfd:0.0.1
gsutil defacl ch -u AllUsers:R gs://artifacts.hightowerlabs.appspot.com
gsutil acl ch -r -u AllUsers:R gs://artifacts.hightowerlabs.appspot.com
rm konfd
