#!/bin/bash
./build
docker build -t gcr.io/hightowerlabs/konfd:v0.0.4 .
gcloud docker -- push gcr.io/hightowerlabs/konfd:v0.0.4
gsutil defacl ch -u AllUsers:R gs://artifacts.hightowerlabs.appspot.com
gsutil acl ch -r -u AllUsers:R gs://artifacts.hightowerlabs.appspot.com
rm konfd
